apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-pod
  namespace: nginx-app
spec:
  replicas: 3
  selector: 
    matchLabels: 
      app: production
  template:
    metadata:
      labels:
        app: production
    spec:
      containers: 
      - name: nginx-container
        image: nginx
